# Generated by Django 4.2.3 on 2023-07-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_handler", "0001_text_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextButtonSlugArhive",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "button",
                    models.PositiveIntegerField(
                        verbose_name="ButtonSlug.id: для восстановления публикации"
                    ),
                ),
                (
                    "text",
                    models.PositiveIntegerField(
                        verbose_name="Text.id: для восстановления публикации"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        null=True,
                        verbose_name="TextButtonSlug.order: для восстановления публикации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Архив моделей: Кнопка на текст",
                "verbose_name_plural": "Архив моделей: Кнопки на текст",
            },
        ),
    ]
