name: CI

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  lint-black:
    name: Black code formatter
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: formatter
        uses: psf/black@stable
        with:
          src: "."
          options: "--diff"

  bot-lint-flake:
    name: Bot Check PEP8 codestyle
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bot

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          pip install pipx
          pipx install poetry==1.5.1

      - name: Validate the structure of the pyproject.toml
        run: |
          poetry check

      - name: Verify that poetry.lock is consistent with pyproject.toml
        run: poetry lock --check

      - name: Install dependencies
        run: poetry install --with test

      - name: Test with flake8
        run: poetry run python -m flake8

  expert-system-lint-flake:
    name: Expert System Check PEP8 codestyle
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./expert-system

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          pip install pipx
          pipx install poetry==1.5.1

      - name: Validate the structure of the pyproject.toml
        run: |
          poetry check

      - name: Verify that poetry.lock is consistent with pyproject.toml
        run: poetry lock --check

      - name: Install dependencies
        run: poetry install --with test

      - name: Test with flake8
        run: poetry run python -m flake8

  registration-system-lint-flake:
    name: Registration System Check PEP8 codestyle
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./registration-system

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          pip install pipx
          pipx install poetry==1.5.1

      - name: Validate the structure of the pyproject.toml
        run: |
          poetry check

      - name: Verify that poetry.lock is consistent with pyproject.toml
        run: poetry lock --check

      - name: Install dependencies
        run: poetry install --with test

      - name: Test with flake8
        run: poetry run python -m flake8
